### ISSUE TITLE
Não rodou nos testes iniciais.

### ISSUE THREAD

**Issue by algebraic-dev** [giancarlopro/rinha-de-compiler#3]
Não tenho certeza do pq ~ vou investigar.

**Comment by giancarlopro** [comment]
po, estranho né, era pra funcionar, tem um [workflow](https://github.com/giancarlopro/rinha-de-compiler/blob/main/.github/workflows/run_rinha_samples.yml) rodando aqui que clona o repositório da rinha e roda todos exemplos que tem lá usando o docker e todos funcionam.

**Comment by algebraic-dev** [comment]
Agora foi!!
